version: '3.7'

services:

  postgres:
    image: postgres:15.4-alpine3.18
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data:/var/lib/postgresql/data

  payment-service:
    image: "alhon05/payment-service:${VERSION}"
    volumes: 
      - payment_service_data:/services/payment
    ports:
      - 4001:4001
    networks:
      - postgres_network
    depends_on:
      - postgres-db

volumes:
  postgres-data:
  payment_service_data:

networks:
  postgres_network:



